<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE Constitution_Satisfaction_Survey_Results_2012 [
<!ELEMENT Constitution_Satisfaction_Survey_Results_2012 (report)>

<!ELEMENT report (id, q1a_quality_of_police_services, q1b_quality_of_fire_and_emergency, q1c_countys_emergency_preparedness, q1d_county_parks_recreation_programs, q1e_county_arts_cultural_programs, q1f_maintenance_of_county_streets, q1g_traffic_flow_on_county_streets, q1h_county_water_and_wastewater_services, q1i_countys_stormwater_runoff_system)>

<!ELEMENT id (#PCDATA)>
<!ELEMENT q1a_quality_of_police_services (#PCDATA)>
<!ELEMENT q1b_quality_of_fire_and_emergency (#PCDATA)>
<!ELEMENT q1c_countys_emergency_preparedness (#PCDATA)>
<!ELEMENT q1d_county_parks_recreation_programs (#PCDATA)>
<!ELEMENT q1e_county_arts_cultural_programs (#PCDATA)>
<!ELEMENT q1f_maintenance_of_county_streets (#PCDATA)>
<!ELEMENT q1g_traffic_flow_on_county_streets (#PCDATA)>
<!ELEMENT q1h_county_water_and_wastewater_services (#PCDATA)>
<!ELEMENT q1i_countys_stormwater_runoff_system (#PCDATA)>

<!ATTLIST report row CDATA #REQUIRED>


]>

<Constitution_Satisfaction_Survey_Results_2012>


	<report id = "row 1">

		<id>325</id>
		<q1a_quality_of_police_services>9 - Don't Know</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>9 - Don't Know</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>9 - Don't Know</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>5 - Very Satisfied</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>5 - Very Satisfied</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>5 - Very Satisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>3 - Neutral</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>4 - Satisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>3 - Neutral</q1i_countys_stormwater_runoff_system>

	</report>



	<report id = "row 2">

		<id>74</id>
		<q1a_quality_of_police_services>3 - Neutral</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>4 - Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>3 - Neutral</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>5 - Very Satisfied</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>3 - Neutral</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>2 - Dissatisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>3 - Neutral</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>5 - Very Satisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>4 - Satisfied</q1i_countys_stormwater_runoff_system>


	</report>



	<report id = "row 3">

		<id>343</id>
		<q1a_quality_of_police_services>3 - Neutral</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>4 - Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>3 - Neutral</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>3 - Neutral</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>3 - Neutral</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>3 - Neutral</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>3 - Neutral</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>3 - Neutral</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>3 - Neutral</q1i_countys_stormwater_runoff_system>

		


		
	</report>


	<report id = "row 4">

		<id>276</id>
		<q1a_quality_of_police_services>4 - Satisfied</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>5 - Very Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>3 - Neutral</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>4 - Satisfied</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>4 - Satisfied</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>4 - Satisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>1 - Very Dissatisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>9 - Don't Know</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>9 - Don't Know</q1i_countys_stormwater_runoff_system>

		
	</report>

	<report id = "row 5">

		<id>6</id>
		<q1a_quality_of_police_services>9 - Don't Know</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>9 - Don't Know</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>9 - Don't Know</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>9 - Don't Know</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>9 - Don't Know</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>1 - Very Dissatisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>1 - Very Dissatisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>9 - Don't Know</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>9 - Don't Know</q1i_countys_stormwater_runoff_system>

		
	</report>



	<report id = "row 6">

		<id>256</id>
		<q1a_quality_of_police_services>4 - Satisfied</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>4 - Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>4 - Satisfied</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>9 - Don't Know</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>5 - Very Satisfied</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>4 - Satisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>4 - Satisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>5 - Very Satisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>5 - Very Satisfied</q1i_countys_stormwater_runoff_system>

		
	</report>


	<report id = "row 7">

		<id>1061</id>
		<q1a_quality_of_police_services>4 - Satisfied</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>4 - Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>4 - Satisfied</q1c_countys_emergency_preparedness>
		<q1d_county_parks_recreation_programs>5 - Very Satisfied</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>4 - Satisfied</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>4 - Satisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>4 - Satisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>5 - Very Satisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>5 - Very Satisfied</q1i_countys_stormwater_runoff_system>

		
	</report>

	<report id = "row 8">

		<id>521</id>
		<q1a_quality_of_police_services>4 - Satisfied</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>9 - Don't Know</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness>9 - Don't Know</q1c_countys_emergency_preparedness>	
		<q1d_county_parks_recreation_programs>9 - Don't Know</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>9 - Don't Know</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>4 - Satisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>4 - Satisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>3 - Neutral</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>9 - Don't Know</q1i_countys_stormwater_runoff_system>

		
	</report>


	<report id = "row 9">

		<id>1205</id>
		<q1a_quality_of_police_services>4 - Satisfied</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>4 - Satisfied</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness3>9 - Don't Know</q1c_countys_emergency_preparedness3>
		<q1d_county_parks_recreation_programs>4 - Satisfied</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>9 - Don't Know</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>2 - Dissatisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>2 - Dissatisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>2 - Dissatisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>9 - Don't Know</q1i_countys_stormwater_runoff_system>

		
	</report>


	


	<report id = "row 10">

		<id>174</id>
		<q1a_quality_of_police_services>3 - Neutral</q1a_quality_of_police_services>
		<q1b_quality_of_fire_and_emergency>9 - Don't Know</q1b_quality_of_fire_and_emergency>
		<q1c_countys_emergency_preparedness3>9 - Don't Know</q1c_countys_emergency_preparedness3>
		<q1d_county_parks_recreation_programs>9 - Don't Know</q1d_county_parks_recreation_programs>
		<q1e_county_arts_cultural_programs>4 - Satisfied</q1e_county_arts_cultural_programs>
		<q1f_maintenance_of_county_streets>2 - Dissatisfied</q1f_maintenance_of_county_streets>
		<q1g_traffic_flow_on_county_streets>4 - Satisfied</q1g_traffic_flow_on_county_streets>
		<q1h_county_water_and_wastewater_services>5 - Very Satisfied</q1h_county_water_and_wastewater_services>
		<q1i_countys_stormwater_runoff_system>9 - Don't Know</q1i_countys_stormwater_runoff_system>

		
	</report>




</Constitution_Satisfaction_Survey_Results_2012>

